### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by ezraarisi** [joeljsv/hacktober2021#110]
can we also have something together, like a discord to have a mini havkathon this month?

**Comment by prehans** [comment]
Yes @azraft277 .

**Comment by ghost** [comment]
What to add to this? - @joeljsv  please 🙏🏻 tell me...and I will fix it

**Comment by joeljsv** [comment]
> What to add to this? - @joeljsv please 🙏🏻 tell me...and I will fix it

you can add your projects or contribute some implementation of algorithms or solutions for competitive coding problems.

**Comment by joeljsv** [comment]
> can we also have something together, like a discord to have a mini hackathon this month?

Sorry bro in our campus already we are hosting hackthon.
