### ISSUE TITLE
Hacktober'21

### ISSUE THREAD

**Issue by joeljsv** [joeljsv/hacktober2021#49]
Hacktober fest 2021 contribute your codes to this repo :)

**Comment by Adwaita10** [comment]
Can I add a simple Tetris game in python?  I am a beginner trying to learn python through simple projects.

**Comment by anonsecteaminc** [comment]
Hi acc me pull me

**Comment by arjunpundir1106** [comment]
@joeljsv can i add merge_sort algorithm in cpp if you assign this to me?

**Comment by joeljsv** [comment]
@Adwaita10 you are assigned in this issue 👍🏼

**Comment by joeljsv** [comment]
@arjunpundir1106 you are assigned in this issue 👍🏼

**Comment by utkarsh-1905** [comment]
Can I add a International Space Station tracker app which I recently created in JavaScript ?

**Comment by ignaviaa** [comment]
hi would like to contribute too,
can you assign the issue to me?

**Comment by QAZMLP12345** [comment]
Can I add, to find the median of two sorted array in efficient time ? in c++.
Can you assign me?

**Comment by joeljsv** [comment]
> Hii, I would love to contribute. Kindly assign me this issue

ready to go :)

**Comment by yadavsonu21** [comment]
Hi

**Comment by utkarsh-1905** [comment]
Hi, I would like to add a webpage made with vanilla js which displays pokemon sprites along with their names using API calls.
Can I contribute that to this repository?

**Comment by joeljsv** [comment]
> Hi, I would like to add a webpage made with vanilla js which displays pokemon sprites along with their names using API calls. Can I contribute that to this repository?

yes :)

**Comment by sahilvaidya13** [comment]
I want to add some ds algos. Can i contribute?

**Comment by prajjwaljoshi** [comment]
can i add quick_sort algorithm in cpp? i just started learning cpp and want to contribute. Thanks

**Comment by vibhuti019** [comment]
can I add a python based weather and time desktop plugin made using Tkinter?

**Comment by nish2447** [comment]
hey can I add one pinterest clone here? Flutter is used

**Comment by ktra99** [comment]
Hey! @joeljsv 

I would like to contribute a project that I'm currently working on. It's built using Next.JS + Supabase. This is my first time participating in hacktoberfest and in open source in general. Would really appreciate the oppertunity, Thanks!

**Comment by yogeshkumar-1234** [comment]
Can i add the prim's algorithm for minimum spanning tree in graphs

**Comment by thisfardi** [comment]
I have added maincraft CLone in the python codes refer to the #131 pull request. tq

**Comment by prehans** [comment]
@joeljsv can I add codechef snack down problems with solutions.

**Comment by prahenstark** [comment]
@joeljsv  can i add some algorithm codes??

**Comment by SameeraShaikISLAM** [comment]
Hi, I would love to contribute too. can i add my Cobol codes
Kindly assign me

**Comment by shivam-jha2712** [comment]
I have added my folder for API-BASED Advice Generator in the main repo section for that could you please refer to the #158  pull request. Along with that, I have added the description as well. Could you please find it and help me get my 2nd PR

**Comment by abhishekangale** [comment]
Can I add Floyd-Warshall algorithm for all pairs shortest path problem in C++?

**Comment by ignaviaa** [comment]
@joeljsv i have added a python code here mentioned PR #156 pls check it out , if valid merge it.

**Comment by Daltonhensley19** [comment]
Can I add a simple implementation of a Fibonacci number generator in Rust?

**Comment by yadavsonu21** [comment]
Submit it into the respective folder.

**Comment by shivam-jha2712** [comment]
I have submitted an API based meal generator based on key ingredient #186 Please find it and merge it and so as to get my 4th PR done and dusted

**Comment by shivam-jha2712** [comment]
Please, bro, merge this PR #186  as well because I need to get my 4th PR under progress and I can't find any other Repo which is not under the excluded project category and as it is my first time under this fest so please do help me out
